name: Deploy npm project
description: Deploy a previously built npm project to a given server using rsync with ssh key authentication given via the DEPLOY_SSH_KEY secret.

inputs:
  source_directory:
    default: "dist/"
    description: The build result directory to deploy. Defaults to "dist/".
  target_host:
    required: true
    description: The hostname of the target server.
  target_user:
    required: true
    description: The user to connect to the target server with.
  target_directory:
    required: true
    description: The directory to deploy to on the target server. Remember that you need to use "/" if the deploy ssh key is restricted with `rrsync`.
  ssh_key:
    required: true
    description: The private key to use for ssh key authentication.
  rsync_args:
    default: "--delete -rvzci"
    description: The arguments for rsync. Defaults to `--delete -rvzci`.

runs:
  using: "composite"
  steps:
    - name: Deploy build result
      uses: easingthemes/ssh-deploy@v5
      with:
        SSH_PRIVATE_KEY: ${{ inputs.ssh_key }}
        REMOTE_HOST: ${{ inputs.target_host }}
        REMOTE_USER: ${{ inputs.target_user }}
        SOURCE: ${{ inputs.source_directory }}
        TARGET: ${{ inputs.target_directory }}
        ARGS: ${{ inputs.rsync_args }}
