name: Build and deploy npm project on push

on:
  push:

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  on_push:
    uses: poettig/github-ci/workflows/npm/build_and_deploy.yml@main
    secrets: inherit
