name: Build an npm project and deploy to a server (only if the branch is "main" or "development")

on:
  workflow_call:
    secrets:
      DEPLOY_SSH_KEY:
        required: true
    inputs:
      branch:
        type: string
        required: true
        description: The branch to build and deploy.
      node_version:
        type: string
        description: The node version to build with. Defaults to 20.
      npm_build_script:
        type: string
        default: build
        description: The name of the npm script to run for building the branch. `npm ci --omit=dev` is run as a previous step. Defaults to `build`.
      build_env:
        type: string
        default: '{}'
        description: Environment variables passed to the build script as a JSON string.
      target_host:
        type: string
        description: The hostname of the target server.
      target_user:
        type: string
        description: The user to connect to the target server with.
      target_base_directory:
        type: string
        description: The base directory to deploy to. The main branch will deploy to <target_base_directory>/prod, the development branch to <target_base_directory>/staging. The default is and empty string. Must not end with "/". If it does, there will most likely be errors.
      restart_service:
        type: string
        description: A service or space-separated list of services to restart after sucessful deploy.

concurrency:
  group: ci-${{ inputs.branch }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository to get templates
        uses: actions/checkout@v4

      - name: Check if required variables exist
        run: |
          [ -n "${{ inputs.target_host || vars.NODE_VERSION }}" ] || { echo "Both node_version action input variable and NODE_VERSION project CI variable is undefined"; exit 1; } 
          [ -n "${{ inputs.target_host || vars.DEPLOY_HOST }}" ] || { echo "Both target_host action input variable and DEPLOY_HOST project CI variable is undefined"; exit 1; } 
          [ -n "${{ inputs.target_user || vars.DEPLOY_USER }}" ] || { echo "Both target_user action input variable and DEPLOY_USER project CI variable is undefined"; exit 1; } 

      # As action for clean definition and reusability
      - name: Build ${{ github.repository }}
        uses: poettig/github-ci/build_npm@main
        with:
          branch: ${{ inputs.branch }}
          node_version: "${{ inputs.node_version || vars.NODE_VERSION }}"
          npm_build_script: ${{ inputs.npm_build_script }}
          build_env: ${{ inputs.build_env }}

      # As action to only need the if condition once
      - name: Deploy ${{ github.repository }}
        if: "${{ inputs.branch == 'main' || inputs.branch == 'development' }}"
        uses: poettig/github-ci/deploy_npm@main
        with:
          branch: ${{ inputs.branch }}
          target_host: ${{ inputs.target_host || vars.DEPLOY_HOST }}
          target_user: ${{ inputs.target_user || vars.DEPLOY_USER }}
          target_directory: "${{ vars.target_base_directory || vars.DEPLOY_BASE_DIRECTORY || '' }}${{ inputs.branch == 'main' && '/prod' || '/staging' }}"
          ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Restart ${{ inputs.restart_service }}
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ inputs.target_host }}
          username: ${{ inputs.target_user }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: sudo systemctl restart ${{ inputs.restart_service }}
