name: Build an npm project and deploy to a server (only if the branch is "main" or "development")

on:
  workflow_call:
    secrets:
      DEPLOY_SSH_KEY:
        required: true
    inputs:
      branch:
        type: string
        required: true
        description: The branch to build and deploy.
      node_version:
        type: string
        default: "18"
        description: The node version to build with. Defaults to 20.
      npm_build_script:
        type: string
        default: build
        description: The name of the npm script to run for building the branch. `npm ci --omit=dev` is run as a previous step. Defaults to `build`.
      build_env:
        type: string
        description: Environment variables passed to the build script as a JSON string.
      target_host:
        type: string
        required: true
        description: The hostname of the target server.
      target_user:
        type: string
        required: true
        description: The user to connect to the target server with.
      restart_service:
        type: string
        description: A service or space-separated list of services to restart after sucessful deploy.

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository to get templates
        uses: actions/checkout@v4

      # As action for clean definition and reusability
      - name: Build ${{ github.repository }}
        uses: poettig/github-ci/build_npm@main
        with:
          branch: ${{ inputs.branch }}
          node_version: ${{ inputs.node_version }}
          npm_build_script: ${{ inputs.npm_build_script }}
          build_env: ${{ inputs.build_env }}

      # As action to only need the if condition once
      - name: Deploy ${{ github.repository }}
        if: "${{ github.ref_name == 'main' || github.ref_name == 'development' }}"
        uses: poettig/github-ci/deploy_npm@main
        with:
          branch: ${{ inputs.branch }}
          target_host: ${{ inputs.target_host }}
          target_user: ${{ inputs.target_user }}
          target_directory: "${{ github.ref_name == 'main' && '/prod' || '/staging' }}"
          ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Restart ${{ inputs.restart_service }}
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ inputs.target_host }}
          username: ${{ inputs.target_user }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: sudo systemctl restart ${{ inputs.restart_service }}
