name: Test npm_build_and_deploy

on: workflow_dispatch

jobs:
  test:
    uses: poettig/github-ci/.github/workflows/npm_build_and_deploy.yml@main
    secrets:
      DEPLOY_SSH_KEY: "This is just a test, you won't deploy anything."
    with:
      branch: ${{ github.ref_name }}
      node_version: 20
      build_env: |-
        STAGING:${{ github.ref_name != 'main' }}
        !SECRET:testsecret