name: Test npm_build_and_deploy

on: workflow_dispatch

jobs:
  test:
    uses: poettig/github-ci/.github/workflows/npm_build_and_deploy.yml@main
    environment: ${{ github.ref_name == 'main' && 'production' || (github.ref_name == 'development' && 'staging' || '') }}
    with:
      branch: main
      node_version: 20